### ISSUE TITLE
:DogeGenerate files with "Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found" required by treesitter

### ISSUE THREAD

**Issue by ColinKennedy** [kkoomen/vim-doge#305]
**Describe the bug**

I'm unable to use vim-doge's latest version becaus of an error while calling `:DogeGenerate`. Any advice would be greatly appreciated.

**Settings**

**To Reproduce**

- Create file `doge.vim` with:

```vim
set nocompatible
set runtimepath^=/path/to/vim-doge
filetype plugin indent on
syntax on
set hidden
```

- Start neovim with command: `nvim -u doge.vim test.py`

`test.py` looks like this

```python
def thing(foo, bar, blah=8):  # Put your cursor on this line
	return 10
```

- Call `:DogeGenerate`

**Expected behavior**

A docstring should've been generated but instead, it errors with this:

```
DogeGenerate
[DoGe] python parser failed
[Doge] Exception: Vim(return):E474: Unidentified byte: /tmp/caxa/vim-doge/i0glsuay2m/index.js:211
   throw e;
   ^
Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/caxa/vim-doge/i0glsuay2m/build/Release/tree_sitter_runtime_binding.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.8460 (/tmp/caxa/vim-doge/i0glsuay2m/index.js:2728:18)
    at __nccwpck_require__ (/tmp/caxa/vim-doge/i0glsuay2m/index.js:2937:43)
    at Object.9525 (/tmp/caxa/vim-doge/i0glsuay2m/index.js:206:13)
    at __nccwpck_require__ (/tmp/caxa/vim-doge/i0glsuay2m/index.js:2937:43)
    at Object.6144 (/tmp/caxa/vim-doge/i0glsuay2m/index.js:1041:39)
/tmp/caxa/vim-doge/i0glsuay2m/index.js:211
    throw e;
    ^

Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/caxa/vim-doge/i0glsuay2m/build/Release/tree_sitter_runtime_binding.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.8460 (/tmp/caxa/vim-doge/i0glsuay2m/index.js:2728:18)
    at __nccwpck_require__ (/tmp/caxa/vim-doge/i0glsuay2m/index.js:2937:43)
    at Object.9525 (/tmp/caxa/vim-doge/i0glsuay2m/index.js:206:13)
    at __nccwpck_require__ (/tmp/caxa/vim-doge/i0glsuay2m/index.js:2937:43)
    at Object.6144 (/tmp/caxa/vim-doge/i0glsuay2m/index.js:1041:39)
```

**Screenshots**

n/a

**Output of `vim --version`**

```
:version                                                                                                                          
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-
unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-st
rong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_F
ROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim
/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az242-526

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

`:checkhealth` output

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5202'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. |'termguicolors'| won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /bin/python2
  - INFO: Other python executable: /usr/bin/python2
  - INFO: Python version: 2.7.5
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.6.8
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v12.14.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - Perl version is too old, 5.22+ required

## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13
```

**OS**: CentOS Linux release 7.6.1810 (Core)

**Comment by ColinKennedy** [comment]
Nvm figured it out. https://github.com/cdr/code-server/issues/347#issuecomment-478389393 this comment worked.

I compiled gcc 8.2.0 and then 

```
sudo mv /lib64/libstdc++.so.6{,.old}
sudo ln -s ~/path/to/gcc/lib64/libstdc++.so.6.0.25 /lib64/libstdc++.so.6
```

re-ran vim-doge and it worked
