### ISSUE TITLE
[DoGe] php parser failed

### ISSUE THREAD

**Issue by vzytoi** [kkoomen/vim-doge#317]
I just installed vim-doge on Window using packer.nvim and nvim v0.6.0 and tried to make a doc on a php file. It fail with this error. Thank you! (really nice plugin btw) 
```
[DoGe] php parser failed
[Doge] Exception: Vim(return):E474: Unidentified byte: internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\root\AppData\Local\Temp\nvimp0n3iZ\13'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.6144 (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:1058:37)
    at __nccwpck_require__ (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2937:43)
    at C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2954:18
    at Object.<anonymous> (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2955:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\root\\AppData\\Local\\Temp\\n
internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\root\AppData\Local\Temp\nvimp0n3iZ\13'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.6144 (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:1058:37)
    at __nccwpck_require__ (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2937:43)
    at C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2954:18
    at Object.<anonymous> (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2955:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\root\\AppData\\Local\\Temp\\nvimp0n3iZ\\13'
}
[DoGe] php parser failed
[Doge] Exception: Vim(return):E474: Unidentified byte: internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\root\AppData\Local\Temp\nvimp0n3iZ\16'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.6144 (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:1058:37)
    at __nccwpck_require__ (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2937:43)
    at C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2954:18
    at Object.<anonymous> (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2955:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\root\\AppData\\Local\\Temp\\n
internal/fs/utils.js:332
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\root\AppData\Local\Temp\nvimp0n3iZ\16'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.6144 (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:1058:37)
    at __nccwpck_require__ (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2937:43)
    at C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2954:18
    at Object.<anonymous> (C:\Users\root\AppData\Local\Temp\caxa\vim-doge\kr1uh6ehct\index.js:2955:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\root\\AppData\\Local\\Temp\\nvimp0n3iZ\\28'
}
```

**Comment by kkoomen** [comment]
Can you try to install node v15 (you can use nvm for this) and reinstall again? Lately issues are appearing due to the fact node v15 is required.

**Comment by kkoomen** [comment]
@vzytoi  I've done a big upgrade with all the parsers today and have published [v3.12.0](https://github.com/kkoomen/vim-doge/releases/tag/v3.12.0).  Please upgrade locally and test whether or not you still have any issues.

**Comment by vzytoi** [comment]
Hey!
Firstly thank you very much for thinking about me and sorry for not answering your previous message.
I recently switched from Windows 10 to Debian using my second SSD and I'm happy to say that it works perfectly here.
If it can help I'll be glad to try it out on Windows to check how it goes.
Again thank you and sorry for my English (:

**Comment by kkoomen** [comment]
@vzytoi Oh, I forgot that you were using Windows. I did exclude the build for Windows in this version, because of node-gyp being shitty, so no need to test on Windows. Jus keep using Debian :)

I'll just close this issue for now. Feel free to report other issues in the future.
