### ISSUE TITLE
Doge generate on js files

### ISSUE THREAD

**Issue by NicholasKao1029** [kkoomen/vim-doge#322]
**Describe the bug**

When activating `:DogeGenerate` I get the following error
```
Error: Cannot find module '/var/folders/1m/zlhkhsqx67jdg84q85t5jwqc0000gn/T/caxa/vim-doge/tg22fbzk2w/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/folders/1m/zlhkhsqx67jdg84q85t5jwqc0000gn/T/caxa/vim-doge/tg22fbzk2w/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[DoGe] typescript parser failed
[Doge] Exception: Vim(return):E474: Unidentified byte: internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/folders/1m/zlhkhsqx67jdg84q85t5jwqc0000gn/T/caxa/vim-doge/tg22fbzk2w/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/folders/1m/zlhkhsqx67jdg84q85t5jwqc0000gn/T/caxa/vim-doge/tg22fbzk2w/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
[DoGe] typescript parser failed
[Doge] Exception: Vim(return):E474: Unidentified byte: internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/folders/1m/zlhkhsqx67jdg84q85t5jwqc0000gn/T/caxa/vim-doge/tg22fbzk2w/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/folders/1m/zlhkhsqx67jdg84q85t5jwqc0000gn/T/caxa/vim-doge/tg22fbzk2w/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

This is on Mac Big Sur 11.5.2, I `cd` into the above folder and there isn't an index.js only 
```
drwxr-xr-x - 30 Dec 10:25 build
drwxr-xr-x - 30 Dec 10:25 node_modules
drwxr-xr-x - 31 Dec 05:02 src
```

**To Reproduce**

- Create file `doge.vim` with:
```vim
set nocompatible
set runtimepath^=/path/to/vim-doge
filetype plugin indent on
syntax on
set hidden
```

- Start neovim with command: `vim -u doge.vim`

1. edit `temp.js` file anywhere
2. create simple function 
```
function x () {
  return 1;
}
```
hover over x and run `:DogeGenerate`. See error pop up

**Expected behavior**
Run and produce docs, no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/45542006/147834531-62052e05-7b41-4081-8f69-cf006b20a7a2.png)

**Output of `vim --version`**

running neovim
```
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.6.0/share/nvim"

Run :checkhealth for more info
```

I've tried reinstalling doge-vim multiple times as well.
Using `Plug` as plugin manager

**Comment by NicholasKao1029** [comment]
https://github.com/kkoomen/vim-doge/issues/319 Looks very relevant 

https://github.com/kkoomen/vim-doge/issues/317 potentially relevant

**Comment by kkoomen** [comment]
Can you try to install node v15 (you can use nvm for this) and reinstall again? Lately issues are appearing due to the fact node v15 is required.

**Comment by NicholasKao1029** [comment]
@kkoomen Thanks that solved the issue! 

No worries I appreciate the work you've put in, could I set up a PR for the README to note the node version dependency?

**Comment by kkoomen** [comment]
> @kkoomen Thanks that solved the issue! 
> 
> 
> 
> No worries I appreciate the work you've put in, could I set up a PR for the README to note the node version dependency?

I'll do it this evening. Thanks though!

**Comment by jeffschwartz** [comment]
I have the same issue when activating :DogeGenerate. I get the following error:

Screenshot:

<img width="2240" alt="Screen Shot 2022-03-28 at 11 40 00 PM" src="https://user-images.githubusercontent.com/271288/160532129-09f6fc74-1bab-4647-83d6-054a74e17c24.png">

Output of running nvim -v:

```shell
NVIM v0.7.0-dev+1295-g04d2476d3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jeffreyschwartz@home

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-04d2476/share/nvim"

Features: +acl +iconv +tui
```

Environment:
Mac OS: v12.3
Hardware: M1 Mac
