### ISSUE TITLE
binary version requires GLIBC_2.32 and does not work on Ubuntu 20.04 (glibc 2.31)

### ISSUE THREAD

**Issue by r7vme** [kkoomen/vim-doge#514]
**Describe the bug**

Thanks for the plugin!

I recently noticed that vim-doge crashes with

```
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/caxa/applications/vim-doge/hqhcvuqe6w/0/build/Release/tree_sitter_r
untime_binding.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.8460 (/tmp/caxa/applications/vim-doge/hqhcvuqe6w/0/index.js:1:50531)
    at __nccwpck_require__ (/tmp/caxa/applications/vim-doge/hqhcvuqe6w/0/index.js:1:438868)
    at Object.9525 (/tmp/caxa/applications/vim-doge/hqhcvuqe6w/0/index.js:1:2465)
    at __nccwpck_require__ (/tmp/caxa/applications/vim-doge/hqhcvuqe6w/0/index.js:1:438868)
    at Object.6144 (/tmp/caxa/applications/vim-doge/hqhcvuqe6w/0/index.js:1:17145) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Workaround**

use version from source with
```
Plug 'kkoomen/vim-doge', { 'do': 'npm i --no-save && npm run build:binary:unix' }
```

**Settings**

**To Reproduce**

1. ubuntu 20.04 (`ldd --version` ldd (Ubuntu GLIBC 2.31-0ubuntu9.2) 2.31) , nodejs 16, neovim 0.8.2, vim-doge binary version v3.19.0
2. navigate to any python/c++ class/function and press the keymapping
3. fails with long traceback, in the end of the traceback error above

**Expected behavior**

works

**Screenshots**

**Output of `./bin/vim-doge --version`**

**Output of `vim --version`**

**Comment by kkoomen** [comment]
@leafac Any idea? Seems to come from your package.

**Comment by leafac** [comment]
@kkoomen The issue doesn’t have to do with caxa.

What’s happening is that `tree_sitter_runtime_binding.node` was built to dynamically link to glibc 2.32, but the @r7vme’s operating system provides glibc 2.31.

Most probably `tree_sitter_runtime_binding.node` doesn’t actually use anything from the newer version of glibc, so you may make vim-doge’s binary more compatible with older versions of Ubuntu by switching [from `ubuntu-latest`](https://github.com/kkoomen/vim-doge/blob/f58b46b6fb164c0eadfc47c4d6ebb10decb7fd37/.github/workflows/release.yml#L13) (which is Ubuntu 22.04 at this point) to `ubuntu-20.04`.

**Comment by kkoomen** [comment]
> @kkoomen The issue doesn’t have to do with caxa.
> 
> What’s happening is that `tree_sitter_runtime_binding.node` was built to dynamically link to glibc 2.32, but @r7vme’s operating system provides glibc 2.31.
> 
> Most probably `tree_sitter_runtime_binding.node` doesn’t actually use anything from the newer version of glibc, so you may make vim-doge’s binary more compatible with older versions of Ubuntu by switching [from `ubuntu-latest`](https://github.com/kkoomen/vim-doge/blob/f58b46b6fb164c0eadfc47c4d6ebb10decb7fd37/.github/workflows/release.yml#L13) (which is Ubuntu 22.04 at this point) to `ubuntu-20.04`.

@leafac Alrighty, I'll try that, thanks for now.

**Comment by kkoomen** [comment]
@r7vme To confirm, building manually with `npm i --no-save && npm run build:binary:unix` does work for you, right?

**Comment by r7vme** [comment]
@kkoomen yep `npm i --no-save && npm run build:binary:unix` works

**Comment by kkoomen** [comment]
@r7vme Please try the new v3.19.1 version with the binary. Make sure to run `rm -rf vim-doge/bin/` locally before running `:PlugUpdate` or `call doge#install()`.

Let me know if the new binary works.

**Comment by r7vme** [comment]
@kkoomen latest v3.19.1 works both on 22.04 and 20.04! Thank you!

**Comment by kkoomen** [comment]
@r7vme Awesome! Thanks to @leafac as well for this solution!
